# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
# first 10 terms will be:
#                             1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
# even-valued terms.

cursor_a = 1
cursor_b = 2
sum_of_even_terms = 0
if cursor_a % 2 == 0:
    sum_of_even_terms += cursor_a
if cursor_b % 2 == 0:
    sum_of_even_terms += cursor_b
while cursor_a + cursor_b <= 4000000:
    temp = cursor_a + cursor_b
    if temp % 2 == 0:
        sum_of_even_terms += temp
    cursor_a = cursor_b
    cursor_b = temp

print(sum_of_even_terms)
