#include <stdio.h>

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
int main()
{
    int first_index = 3;
    int second_index = 2;
    int fib_next = 0;
    int sum = 2;
    while(first_index <= 4000000)
    {
        fib_next = first_index + second_index;
        second_index = first_index;
        first_index = fib_next;
        if(fib_next % 2 == 0)
        {
            sum += fib_next;
        }
    }
    printf("\r\n%d\n", sum);

    return 0;
}